bootstrap:
  memory_lock: true

http:
  port: "9200"

path:
  data: /usr/share/elasticsearch/data
  logs: /usr/share/elasticsearch/logs

transport:
  port: "9300"

network:
  host: data-2.purwandi.id
  publish_host: data-2.purwandi.id
  bind_host: 0.0.0.0

cluster:
  name: elastic

discovery:
  initial_state_timeout: 10m
  seed_hosts:
    - master-1.purwandi.id
    - master-2.purwandi.id
    - master-3.purwandi.id
    - data-1.purwandi.id
    - data-2.purwandi.id

node: 
  name: data-2.purwandi.id
  roles:
    - data
    - data_content
    - data_warm
    - data_cold
    - data_frozen
    - remote_cluster_client

xpack:
  security:
    enabled: true
    http:
      ssl:
        enabled: true
        key: /usr/share/elasticsearch/config/certs/elasticsearch.purwandi.id.key
        certificate: /usr/share/elasticsearch/config/certs/elasticsearch.purwandi.id.crt
        certificate_authorities: /usr/share/elasticsearch/config/certs/purwandi.id.crt
    transport:
      ssl:
        enabled: true
        verification_mode: full
        key: /usr/share/elasticsearch/config/certs/elasticsearch.purwandi.id.key
        certificate: /usr/share/elasticsearch/config/certs/elasticsearch.purwandi.id.crt
        certificate_authorities: /usr/share/elasticsearch/config/certs/purwandi.id.crt